Data Profiling

In [71]:
# import libraries
import pandas as pd
import numpy as np
import os

In [72]:
#load datasets
data_path = r"C:\Users\sarga\Documents\VIT\DE\Procurement-Data-Platform\datasets"

purchase_orders = pd.read_excel(os.path.join(data_path, "purchase_orders.xlsx"))
suppliers = pd.read_csv(os.path.join(data_path, "suppliers.csv"))
warehouses = pd.read_json(os.path.join(data_path, "warehouse.json"))
contracts = pd.read_csv(os.path.join(data_path, "contracts.csv"))
inventory = pd.read_json(os.path.join(data_path, "inventory.json"))
invoices = pd.read_xml(os.path.join(data_path, "invoices.xml"))

In [73]:
#Create a dataset dictionary
datasets = {
    "Purchase Orders": purchase_orders,
    "Suppliers": suppliers,
    "Warehouses": warehouses,
    "Contracts": contracts,
    "Inventory": inventory,
    "Invoices": invoices
}

In [74]:
#Check number of rows and columns
for name, df in datasets.items():
    print(name)
    print("Rows:", df.shape[0])
    print("Columns:", df.shape[1])
    print("-" * 40)

Purchase Orders
Rows: 5000
Columns: 23
----------------------------------------
Suppliers
Rows: 250
Columns: 10
----------------------------------------
Warehouses
Rows: 10
Columns: 8
----------------------------------------
Contracts
Rows: 600
Columns: 10
----------------------------------------
Inventory
Rows: 5000
Columns: 14
----------------------------------------
Invoices
Rows: 5000
Columns: 13
----------------------------------------

In [75]:
#Check column names and data types
for name, df in datasets.items():
    print("\n", name)
    print(df.dtypes)

 Purchase Orders
PO_ID                      object
PO_Date                    object
Supplier_ID                object
Product_ID                 object
Warehouse_ID               object
Contract_ID                object
Supply_Type                object
Quantity                    int64
Unit_Cost_INR             float64
Subtotal_INR              float64
Freight_INR               float64
Import_Duty_Percent       float64
Import_Duty_INR           float64
Tax_INR                   float64
Total_PO_Value_INR        float64
Currency                   object
Exchange_Rate_to_INR      float64
Shipping_Mode              object
Expected_Delivery_Date     object
Actual_Receipt_Date        object
Delay_Days                  int64
Approval_Status            object
PO_Status                  object
dtype: object

 Suppliers
Supplier_ID               object
Supplier_Name             object
Supplier_Type             object
Supplier_Country          object
Supplier_City             object
Primary_Category          object
Supplier_Rating           object
Typical_Lead_Time_Days     int64
Supplier_Status           object
Currency                  object
dtype: object

 Warehouses
Warehouse_ID         object
Warehouse_Name       object
City                 object
Country              object
Warehouse_Type       object
Capacity_Units        int64
Storage_Condition    object
Warehouse_Status     object
dtype: object

 Contracts
Contract_ID            object
Supplier_ID            object
Contract_Name          object
Start_Date             object
End_Date               object
Contract_Value        float64
Currency               object
Contract_Type          object
Contract_Status        object
Payment_Terms_Days      int64
dtype: object

 Inventory
Inventory_ID                     object
PO_ID                            object
Product_ID                       object
Warehouse_ID                     object
Snapshot_Date                    object
Opening_Stock                     int64
Stock_In                          int64
Stock_Out                         int64
Closing_Stock                     int64
Reorder_Level                     int64
Safety_Stock                      int64
Inventory_Value_INR             float64
Stock_Status                     object
Capacity_Utilization_Percent    float64
dtype: object

 Invoices
Invoice_ID                  object
PO_ID                       object
Supplier_ID                 object
Invoice_Date                object
Receipt_Date                object
Due_Date                    object
Invoice_Amount_INR         float64
Currency                    object
Exchange_Rate_to_INR         int64
Payment_Status              object
Paid_Date                   object
Matching_Status             object
Invoice_Approval_Status     object
dtype: object

In [76]:
#Check missing values
for name, df in datasets.items():
    print("\n", name)
    print(df.isnull().sum())

 Purchase Orders
PO_ID                       0
PO_Date                     0
Supplier_ID                 0
Product_ID                  0
Warehouse_ID                0
Contract_ID               276
Supply_Type                 0
Quantity                    0
Unit_Cost_INR               0
Subtotal_INR                0
Freight_INR                 0
Import_Duty_Percent         0
Import_Duty_INR             0
Tax_INR                     0
Total_PO_Value_INR          0
Currency                    0
Exchange_Rate_to_INR        0
Shipping_Mode               0
Expected_Delivery_Date      0
Actual_Receipt_Date         0
Delay_Days                  0
Approval_Status             0
PO_Status                   0
dtype: int64

 Suppliers
Supplier_ID               0
Supplier_Name             0
Supplier_Type             0
Supplier_Country          0
Supplier_City             0
Primary_Category          0
Supplier_Rating           0
Typical_Lead_Time_Days    0
Supplier_Status           0
Currency                  0
dtype: int64

 Warehouses
Warehouse_ID         0
Warehouse_Name       0
City                 0
Country              0
Warehouse_Type       0
Capacity_Units       0
Storage_Condition    0
Warehouse_Status     0
dtype: int64

 Contracts
Contract_ID           0
Supplier_ID           0
Contract_Name         0
Start_Date            0
End_Date              0
Contract_Value        0
Currency              0
Contract_Type         0
Contract_Status       0
Payment_Terms_Days    0
dtype: int64

 Inventory
Inventory_ID                    0
PO_ID                           0
Product_ID                      0
Warehouse_ID                    0
Snapshot_Date                   0
Opening_Stock                   0
Stock_In                        0
Stock_Out                       0
Closing_Stock                   0
Reorder_Level                   0
Safety_Stock                    0
Inventory_Value_INR             0
Stock_Status                    0
Capacity_Utilization_Percent    0
dtype: int64

 Invoices
Invoice_ID                    0
PO_ID                         0
Supplier_ID                   0
Invoice_Date                  0
Receipt_Date                  0
Due_Date                      0
Invoice_Amount_INR            0
Currency                      0
Exchange_Rate_to_INR          0
Payment_Status                0
Paid_Date                  1630
Matching_Status               0
Invoice_Approval_Status       0
dtype: int64

In [77]:
#Check duplicates
for name, df in datasets.items():
    print(name, "\nduplicate rows:", df.duplicated().sum())
    print("-" * 40)

Purchase Orders
duplicate rows: 0
----------------------------------------
Suppliers
duplicate rows: 0
----------------------------------------
Warehouses
duplicate rows: 0
----------------------------------------
Contracts
duplicate rows: 0
----------------------------------------
Inventory
duplicate rows: 0
----------------------------------------
Invoices
duplicate rows: 0
----------------------------------------

In [78]:
#duplicate primary keys
primary_keys = {
    "Purchase Orders": "Product_ID",
    "Suppliers": "Supplier_ID",
    "Warehouses": "Warehouse_ID",
    "Contracts": "Contract_ID",
    "Inventory": "Inventory_ID",
    "Invoices": "Invoice_ID"
}

for name, df in datasets.items():
    key = primary_keys[name]
    print(name)
    print("Duplicate", key, ":", df[key].duplicated().sum())
    print()

Purchase Orders
Duplicate Product_ID : 4700

Suppliers
Duplicate Supplier_ID : 0

Warehouses
Duplicate Warehouse_ID : 0

Contracts
Duplicate Contract_ID : 0

Inventory
Duplicate Inventory_ID : 0

Invoices
Duplicate Invoice_ID : 0

In [79]:
#Check basic statistics
for name, df in datasets.items():
    print("\n", name)
    display(df.describe())

 Purchase Orders

,Quantity,Unit_Cost_INR,Subtotal_INR,Freight_INR,Import_Duty_Percent,Import_Duty_INR,Tax_INR,Total_PO_Value_INR,Exchange_Rate_to_INR,Delay_Days
count,5000.000000,5000.000000,5.000000e+03,5.000000e+03,5000.000000,5.000000e+03,5.000000e+03,5.000000e+03,5000.000000,5000.000000
mean,513.416800,45647.136648,2.350277e+07,4.415225e+05,5.033298,1.184048e+06,3.254290e+06,2.838263e+07,30.014536,1.451400
std,286.018167,24030.791375,1.920707e+07,4.891583e+05,6.012039,2.054940e+06,3.001970e+06,2.321438e+07,38.423279,2.383689
min,10.000000,385.220000,5.096080e+03,3.831000e+01,0.000000,0.000000e+00,9.241900e+02,6.058580e+03,0.560000,0.000000
25%,267.000000,26563.415000,7.503377e+06,1.047683e+05,0.000000,0.000000e+00,9.256132e+05,9.064173e+06,1.000000,0.000000
50%,523.000000,44674.130000,1.889416e+07,2.821170e+05,1.000000,1.126325e+03,2.337941e+06,2.273666e+07,1.000000,0.000000
75%,760.000000,66541.400000,3.539231e+07,6.008577e+05,10.032500,1.575361e+06,4.702517e+06,4.289306e+07,62.000000,2.000000
max,1000.000000,93178.590000,8.923069e+07,3.745332e+06,18.000000,1.408533e+07,1.596581e+07,1.133647e+08,106.000000,12.000000

 Suppliers

       Typical_Lead_Time_Days
count              250.000000
mean                17.508000
std                  7.959356
min                  5.000000
25%                 11.000000
50%                 17.000000
75%                 24.000000
max                 30.000000

 Warehouses

       Capacity_Units
count       10.000000
mean     20878.500000
std       6808.841707
min       5767.000000
25%      18994.000000
50%      21967.000000
75%      25795.250000
max      28951.000000

 Contracts

       Contract_Value  Payment_Terms_Days
count    6.000000e+02          600.000000
mean     7.616079e+06           56.925000
std      4.343741e+06           22.299061
min      1.724478e+05           30.000000
25%      3.768706e+06           45.000000
50%      7.690013e+06           60.000000
75%      1.141667e+07           90.000000
max      1.499659e+07           90.000000

 Inventory

,Opening_Stock,Stock_In,Stock_Out,Closing_Stock,Reorder_Level,Safety_Stock,Inventory_Value_INR,Capacity_Utilization_Percent
count,5000.000000,5000.000000,5000.000000,5000.000000,5000.000000,5000.000000,5.000000e+03,5000.000000
mean,525.623400,513.416800,392.202600,654.579800,264.511800,126.388600,2.964971e+07,3.769950
std,439.993149,286.018167,337.239427,498.282645,135.942021,70.415692,3.011763e+07,4.166375
min,0.000000,10.000000,0.000000,0.000000,22.000000,11.000000,0.000000e+00,0.000000
25%,152.750000,267.000000,112.750000,247.000000,163.000000,65.000000,6.940223e+06,1.210000
50%,410.000000,523.000000,293.000000,571.000000,256.000000,118.000000,2.038508e+07,2.780000
75%,796.000000,760.000000,609.000000,976.000000,379.000000,184.000000,4.284091e+07,4.910000
max,1980.000000,1000.000000,1497.000000,2589.000000,499.000000,250.000000,1.942664e+08,41.270000

 Invoices

       Invoice_Amount_INR  Exchange_Rate_to_INR
count        5.000000e+03           5000.000000
mean         2.838263e+07             29.828200
std          2.321438e+07             38.333262
min          6.058580e+03              0.000000
25%          9.064173e+06              1.000000
50%          2.273666e+07              1.000000
75%          4.289306e+07             62.000000
max          1.133647e+08            106.000000

In [80]:
#Create one overall profiling report
profiling_report = []

for name, df in datasets.items():
    for column in df.columns:
        profiling_report.append({
            "Dataset": name,
            "Column": column,
            "Data_Type": str(df[column].dtype),
            "Total_Records": len(df),
            "Missing_Values": df[column].isnull().sum(),
            "Missing_%": round(df[column].isnull().mean() * 100, 2),
            "Unique_Values": df[column].nunique(),
            "Duplicate_Values": df[column].duplicated().sum()
        })

profiling_report = pd.DataFrame(profiling_report)

display(profiling_report)

,Dataset,Column,Data_Type,Total_Records,Missing_Values,Missing_%,Unique_Values,Duplicate_Values
0,Purchase Orders,PO_ID,object,5000,0,0.0,5000,0
1,Purchase Orders,PO_Date,object,5000,0,0.0,581,4419
2,Purchase Orders,Supplier_ID,object,5000,0,0.0,250,4750
3,Purchase Orders,Product_ID,object,5000,0,0.0,300,4700
4,Purchase Orders,Warehouse_ID,object,5000,0,0.0,10,4990
...,...,...,...,...,...,...,...,...
73,Invoices,Exchange_Rate_to_INR,int64,5000,0,0.0,9,4991
74,Invoices,Payment_Status,object,5000,0,0.0,4,4996
75,Invoices,Paid_Date,object,5000,1630,32.6,641,4358
76,Invoices,Matching_Status,object,5000,0,0.0,2,4998
77,Invoices,Invoice_Approval_Status,object,5000,0,0.0,2,4998

Data Quality Report

In [81]:
#Missing-value analysis
missing_report = []

for name, df in datasets.items():
    for column in df.columns:
        missing = df[column].isnull().sum()

        missing_report.append({
            "Dataset": name,
            "Column": column,
            "Missing_Values": missing,
            "Missing_Percentage": round((missing / len(df)) * 100, 2)
        })

missing_report = pd.DataFrame(missing_report)

display(missing_report)

,Dataset,Column,Missing_Values,Missing_Percentage
0,Purchase Orders,PO_ID,0,0.0
1,Purchase Orders,PO_Date,0,0.0
2,Purchase Orders,Supplier_ID,0,0.0
3,Purchase Orders,Product_ID,0,0.0
4,Purchase Orders,Warehouse_ID,0,0.0
...,...,...,...,...
73,Invoices,Exchange_Rate_to_INR,0,0.0
74,Invoices,Payment_Status,0,0.0
75,Invoices,Paid_Date,1630,32.6
76,Invoices,Matching_Status,0,0.0
77,Invoices,Invoice_Approval_Status,0,0.0

In [82]:
#Duplicate analysis
duplicate_report = []

for name, df in datasets.items():
    key = primary_keys[name]

    duplicate_report.append({
        "Dataset": name,
        "Primary_Key": key,
        "Total_Rows": len(df),
        "Duplicate_Rows": df.duplicated().sum(),
        "Duplicate_Keys": df[key].duplicated().sum()
    })

duplicate_report = pd.DataFrame(duplicate_report)

display(duplicate_report)

           Dataset   Primary_Key  Total_Rows  Duplicate_Rows  Duplicate_Keys
0  Purchase Orders    Product_ID        5000               0            4700
1        Suppliers   Supplier_ID         250               0               0
2       Warehouses  Warehouse_ID          10               0               0
3        Contracts   Contract_ID         600               0               0
4        Inventory  Inventory_ID        5000               0               0
5         Invoices    Invoice_ID        5000               0               0

Product_ID is not the primary key of Purchase Orders. A product can appear in many purchase orders.

In [83]:
#Checking Foreign key
def check_foreign_key(child_df, child_column, parent_df, parent_column):
    invalid = child_df[
        ~child_df[child_column].isin(parent_df[parent_column])
    ]

    return len(invalid)

In [84]:
print("Purchase Orders → Suppliers:",
      check_foreign_key(
          purchase_orders,
          "Supplier_ID",
          suppliers,
          "Supplier_ID"
      ))

print("Purchase Orders → Warehouses:",
      check_foreign_key(
          purchase_orders,
          "Warehouse_ID",
          warehouses,
          "Warehouse_ID"
      ))

print("Inventory → Purchase Orders:",
      check_foreign_key(
          inventory,
          "PO_ID",
          purchase_orders,
          "PO_ID"
      ))

print("Inventory → Warehouses:",
      check_foreign_key(
          inventory,
          "Warehouse_ID",
          warehouses,
          "Warehouse_ID"
      ))

print("Invoices → Purchase Orders:",
      check_foreign_key(
          invoices,
          "PO_ID",
          purchase_orders,
          "PO_ID"
      ))

print("Invoices → Suppliers:",
      check_foreign_key(
          invoices,
          "Supplier_ID",
          suppliers,
          "Supplier_ID"
      ))

Purchase Orders → Suppliers: 0
Purchase Orders → Warehouses: 0
Inventory → Purchase Orders: 0
Inventory → Warehouses: 0
Invoices → Purchase Orders: 0
Invoices → Suppliers: 0

Clean and Standardize

In [85]:
# Create copies so the original datasets are not changed
suppliers_clean = suppliers.copy()
contracts_clean = contracts.copy()
warehouses_clean = warehouses.copy()
purchase_orders_clean = purchase_orders.copy()
inventory_clean = inventory.copy()
invoices_clean = invoices.copy()

In [86]:
#Standardize column names
def standardize_columns(df):
    df.columns = (
        df.columns
        .str.strip()
        .str.replace(" ", "_")
        .str.replace("-", "_")
    )
    return df

suppliers_clean = standardize_columns(suppliers_clean)
warehouses_clean = standardize_columns(warehouses_clean)
purchase_orders_clean = standardize_columns(purchase_orders_clean)
contracts_clean = contracts.drop_duplicates(contracts_clean)
inventory_clean = standardize_columns(inventory_clean)
invoices_clean = standardize_columns(invoices_clean)

In [87]:
#Remove extra spaces from text fields
def clean_text_columns(df):
    for col in df.select_dtypes(include="object").columns:
        df[col] = df[col].str.strip()
    return df

suppliers_clean = clean_text_columns(suppliers_clean)
warehouses_clean = clean_text_columns(warehouses_clean)
purchase_orders_clean = clean_text_columns(purchase_orders_clean)
inventory_clean = clean_text_columns(inventory_clean)
invoices_clean = clean_text_columns(invoices_clean)

In [88]:
#Check the result
cleaned_datasets = {
    "Suppliers": suppliers_clean,
    "Warehouses": warehouses_clean,
    "Contracts": contracts_clean,
    "Purchase Orders": purchase_orders_clean,
    "Inventory": inventory_clean,
    "Invoices": invoices_clean
}

for name, df in cleaned_datasets.items():
    print("\n", name)
    print("Rows:", len(df))
    print("Columns:", len(df.columns))
    print("Duplicate rows:", df.duplicated().sum())
    print("Missing values:", df.isnull().sum().sum())

 Suppliers
Rows: 250
Columns: 10
Duplicate rows: 0
Missing values: 0

 Warehouses
Rows: 10
Columns: 8
Duplicate rows: 0
Missing values: 0

 Contracts
Rows: 600
Columns: 10
Duplicate rows: 0
Missing values: 0

 Purchase Orders
Rows: 5000
Columns: 23
Duplicate rows: 0
Missing values: 276

 Inventory
Rows: 5000
Columns: 14
Duplicate rows: 0
Missing values: 0

 Invoices
Rows: 5000
Columns: 13
Duplicate rows: 0
Missing values: 1630

In [89]:
#Handle Missing Values
purchase_orders_clean["Contract_ID"] = (
    purchase_orders_clean["Contract_ID"]
    .fillna("No Contract"))
print("Missing Contract_ID:",
      purchase_orders_clean["Contract_ID"].isnull().sum())

Missing Contract_ID: 0

In [90]:
#Invoices — Paid_Date
invoices_clean["Paid_Date"] = invoices_clean["Paid_Date"].fillna("Not Paid")

In [91]:
cleaned_datasets = {
    "Suppliers": suppliers_clean,
    "Warehouses": warehouses_clean,
    "Contracts": contracts_clean,
    "Purchase Orders": purchase_orders_clean,
    "Inventory": inventory_clean,
    "Invoices": invoices_clean
}

for name, df in cleaned_datasets.items():
    print(name, "→ Missing values:", df.isnull().sum().sum())

Suppliers → Missing values: 0
Warehouses → Missing values: 0
Contracts → Missing values: 0
Purchase Orders → Missing values: 0
Inventory → Missing values: 0
Invoices → Missing values: 0

In [92]:
#Convert Date Columns
# Purchase Orders
purchase_orders_clean["PO_Date"] = pd.to_datetime(
    purchase_orders_clean["PO_Date"],
    dayfirst=True,
    errors="coerce"
)

purchase_orders_clean["Expected_Delivery_Date"] = pd.to_datetime(
    purchase_orders_clean["Expected_Delivery_Date"],
    dayfirst=True,
    errors="coerce"
)

purchase_orders_clean["Actual_Receipt_Date"] = pd.to_datetime(
    purchase_orders_clean["Actual_Receipt_Date"],
    dayfirst=True,
    errors="coerce"
)

# Contracts
contracts_clean["Start_Date"] = pd.to_datetime(
    contracts_clean["Start_Date"],
    dayfirst=True,
    errors="coerce"
)

contracts_clean["End_Date"] = pd.to_datetime(
    contracts_clean["End_Date"],
    dayfirst=True,
    errors="coerce"
)

# Inventory
inventory_clean["Snapshot_Date"] = pd.to_datetime(
    inventory_clean["Snapshot_Date"],
    dayfirst=True,
    errors="coerce"
)

# Invoices
invoices_clean["Invoice_Date"] = pd.to_datetime(
    invoices_clean["Invoice_Date"],
    dayfirst=True,
    errors="coerce"
)

invoices_clean["Receipt_Date"] = pd.to_datetime(
    invoices_clean["Receipt_Date"],
    dayfirst=True,
    errors="coerce"
)

invoices_clean["Due_Date"] = pd.to_datetime(
    invoices_clean["Due_Date"],
    dayfirst=True,
    errors="coerce"
)

invoices_clean["Paid_Date"] = pd.to_datetime(
    invoices_clean["Paid_Date"],
    dayfirst=True,
    errors="coerce"
)

C:\Users\sarga\AppData\Local\Temp\ipykernel_4864\2754740706.py:3: UserWarning: Parsing dates in %Y-%m-%d format when dayfirst=True was specified. Pass `dayfirst=False` or specify a format to silence this warning.
  purchase_orders_clean["PO_Date"] = pd.to_datetime(
C:\Users\sarga\AppData\Local\Temp\ipykernel_4864\2754740706.py:9: UserWarning: Parsing dates in %Y-%m-%d format when dayfirst=True was specified. Pass `dayfirst=False` or specify a format to silence this warning.
  purchase_orders_clean["Expected_Delivery_Date"] = pd.to_datetime(
C:\Users\sarga\AppData\Local\Temp\ipykernel_4864\2754740706.py:15: UserWarning: Parsing dates in %Y-%m-%d format when dayfirst=True was specified. Pass `dayfirst=False` or specify a format to silence this warning.
  purchase_orders_clean["Actual_Receipt_Date"] = pd.to_datetime(
C:\Users\sarga\AppData\Local\Temp\ipykernel_4864\2754740706.py:42: UserWarning: Parsing dates in %Y/%m/%d %H:%M:%S.%f format when dayfirst=True was specified. Pass `dayfirst=False` or specify a format to silence this warning.
  invoices_clean["Invoice_Date"] = pd.to_datetime(
C:\Users\sarga\AppData\Local\Temp\ipykernel_4864\2754740706.py:48: UserWarning: Parsing dates in %Y/%m/%d %H:%M:%S.%f format when dayfirst=True was specified. Pass `dayfirst=False` or specify a format to silence this warning.
  invoices_clean["Receipt_Date"] = pd.to_datetime(

In [93]:
for name, df in {
    "Purchase Orders": purchase_orders_clean,
    "Contracts": contracts_clean,
    "Inventory": inventory_clean,
    "Invoices": invoices_clean
}.items():
    
    print("\n", name)
    print(df.isnull().sum()[df.isnull().sum() > 0])

 Purchase Orders
Series([], dtype: int64)

 Contracts
Series([], dtype: int64)

 Inventory
Series([], dtype: int64)

 Invoices
Due_Date     3001
Paid_Date    3646
dtype: int64

In [94]:
print(contracts_clean[["Start_Date", "End_Date"]].dtypes)
print(inventory_clean["Snapshot_Date"].dtype)

Start_Date    datetime64[ns]
End_Date      datetime64[ns]
dtype: object
datetime64[ns]

In [95]:
#Standardize Text Columns
def standardize_text(df):
    for col in df.select_dtypes(include="object").columns:
        df[col] = df[col].str.strip()
    return df

In [96]:
purchase_orders_clean = standardize_text(purchase_orders_clean)
suppliers_clean = standardize_text(suppliers_clean)
warehouses_clean = standardize_text(warehouses_clean)
contracts_clean = standardize_text(contracts_clean)
inventory_clean = standardize_text(inventory_clean)
invoices_clean = standardize_text(invoices_clean)

In [97]:
#Check Data Types After Cleaning
for name, df in {
    "Purchase Orders": purchase_orders_clean,
    "Suppliers": suppliers_clean,
    "Warehouses": warehouses_clean,
    "Contracts": contracts_clean,
    "Inventory": inventory_clean,
    "Invoices": invoices_clean
}.items():

    print("\n", name)
    print(df.dtypes)

 Purchase Orders
PO_ID                             object
PO_Date                   datetime64[ns]
Supplier_ID                       object
Product_ID                        object
Warehouse_ID                      object
Contract_ID                       object
Supply_Type                       object
Quantity                           int64
Unit_Cost_INR                    float64
Subtotal_INR                     float64
Freight_INR                      float64
Import_Duty_Percent              float64
Import_Duty_INR                  float64
Tax_INR                          float64
Total_PO_Value_INR               float64
Currency                          object
Exchange_Rate_to_INR             float64
Shipping_Mode                     object
Expected_Delivery_Date    datetime64[ns]
Actual_Receipt_Date       datetime64[ns]
Delay_Days                         int64
Approval_Status                   object
PO_Status                         object
dtype: object

 Suppliers
Supplier_ID               object
Supplier_Name             object
Supplier_Type             object
Supplier_Country          object
Supplier_City             object
Primary_Category          object
Supplier_Rating           object
Typical_Lead_Time_Days     int64
Supplier_Status           object
Currency                  object
dtype: object

 Warehouses
Warehouse_ID         object
Warehouse_Name       object
City                 object
Country              object
Warehouse_Type       object
Capacity_Units        int64
Storage_Condition    object
Warehouse_Status     object
dtype: object

 Contracts
Contract_ID                   object
Supplier_ID                   object
Contract_Name                 object
Start_Date            datetime64[ns]
End_Date              datetime64[ns]
Contract_Value               float64
Currency                      object
Contract_Type                 object
Contract_Status               object
Payment_Terms_Days             int64
dtype: object

 Inventory
Inventory_ID                            object
PO_ID                                   object
Product_ID                              object
Warehouse_ID                            object
Snapshot_Date                   datetime64[ns]
Opening_Stock                            int64
Stock_In                                 int64
Stock_Out                                int64
Closing_Stock                            int64
Reorder_Level                            int64
Safety_Stock                             int64
Inventory_Value_INR                    float64
Stock_Status                            object
Capacity_Utilization_Percent           float64
dtype: object

 Invoices
Invoice_ID                         object
PO_ID                              object
Supplier_ID                        object
Invoice_Date               datetime64[ns]
Receipt_Date               datetime64[ns]
Due_Date                   datetime64[ns]
Invoice_Amount_INR                float64
Currency                           object
Exchange_Rate_to_INR                int64
Payment_Status                     object
Paid_Date                  datetime64[ns]
Matching_Status                    object
Invoice_Approval_Status            object
dtype: object

In [98]:
cleaned_datasets = {
    "Purchase Orders": purchase_orders_clean,
    "Suppliers": suppliers_clean,
    "Warehouses": warehouses_clean,
    "Contracts": contracts_clean,
    "Inventory": inventory_clean,
    "Invoices": invoices_clean
}

for name, df in cleaned_datasets.items():
    print("\n", name)
    print(df.isnull().sum()[df.isnull().sum() > 0])

 Purchase Orders
Series([], dtype: int64)

 Suppliers
Series([], dtype: int64)

 Warehouses
Series([], dtype: int64)

 Contracts
Series([], dtype: int64)

 Inventory
Series([], dtype: int64)

 Invoices
Due_Date     3001
Paid_Date    3646
dtype: int64

Data Quality Validation

In [99]:
#Referential Integrity
def check_foreign_key(child_df, child_column, parent_df, parent_column):
    invalid = child_df[
        ~child_df[child_column].isin(parent_df[parent_column])
    ]
    return len(invalid)

In [108]:
print("Purchase Orders → Suppliers:",
      check_foreign_key(
          purchase_orders_clean,
          "Supplier_ID",
          suppliers_clean,
          "Supplier_ID"
      ))

print("Purchase Orders → Warehouses:",
      check_foreign_key(
          purchase_orders_clean,
          "Warehouse_ID",
          warehouses_clean,
          "Warehouse_ID"
      ))

print("Purchase Orders → Contracts:",
      check_foreign_key(
          purchase_orders_clean,
          "Contract_ID",
          contracts_clean,
          "Contract_ID"
      ))

print("Inventory → Purchase Orders:",
      check_foreign_key(
          inventory_clean,
          "PO_ID",
          purchase_orders_clean,
          "PO_ID"
      ))

print("Inventory → Warehouses:",
      check_foreign_key(
          inventory_clean,
          "Warehouse_ID",
          warehouses_clean,
          "Warehouse_ID"
      ))

print("Invoices → Purchase Orders:",
      check_foreign_key(
          invoices_clean,
          "PO_ID",
          purchase_orders_clean,
          "PO_ID"
      ))

print("Invoices → Suppliers:",
      check_foreign_key(
          invoices_clean,
          "Supplier_ID",
          suppliers_clean,
          "Supplier_ID"
      ))

Purchase Orders → Suppliers: 0
Purchase Orders → Warehouses: 0
Purchase Orders → Contracts: 276
Inventory → Purchase Orders: 0
Inventory → Warehouses: 0
Invoices → Purchase Orders: 0
Invoices → Suppliers: 0

the Purchase Orders → Contracts check will count those as invalid.

That is expected, because "No Contract" is not an actual Contract_ID.

Therefore, for this particular check, exclude "No Contract":

In [101]:
po_with_contract = purchase_orders_clean[
    purchase_orders_clean["Contract_ID"] != "No Contract"
]

print("Purchase Orders → Contracts:",
      check_foreign_key(
          po_with_contract,
          "Contract_ID",
          contracts_clean,
          "Contract_ID"
      ))

Purchase Orders → Contracts: 0

In [102]:
#Range Validation
print("Negative Quantity:",
      (purchase_orders_clean["Quantity"] < 0).sum())

print("Negative Unit Cost:",
      (purchase_orders_clean["Unit_Cost_INR"] < 0).sum())

print("Invalid Import Duty %:",
      ((purchase_orders_clean["Import_Duty_Percent"] < 0) |
       (purchase_orders_clean["Import_Duty_Percent"] > 100)).sum())

print("Negative Total PO Value:",
      (purchase_orders_clean["Total_PO_Value_INR"] < 0).sum())

Negative Quantity: 0
Negative Unit Cost: 0
Invalid Import Duty %: 0
Negative Total PO Value: 0

In [103]:
#inventory
print("Negative Opening Stock:",
      (inventory_clean["Opening_Stock"] < 0).sum())

print("Negative Stock In:",
      (inventory_clean["Stock_In"] < 0).sum())

print("Negative Stock Out:",
      (inventory_clean["Stock_Out"] < 0).sum())

print("Negative Closing Stock:",
      (inventory_clean["Closing_Stock"] < 0).sum())

print("Invalid Capacity Utilization:",
      ((inventory_clean["Capacity_Utilization_Percent"] < 0) |
       (inventory_clean["Capacity_Utilization_Percent"] > 100)).sum())

Negative Opening Stock: 0
Negative Stock In: 0
Negative Stock Out: 0
Negative Closing Stock: 0
Invalid Capacity Utilization: 0

In [104]:
#invoices
print("Negative Invoice Amount:",
      (invoices_clean["Invoice_Amount_INR"] < 0).sum())

print("Negative Exchange Rate:",
      (invoices_clean["Exchange_Rate_to_INR"] < 0).sum())

Negative Invoice Amount: 0
Negative Exchange Rate: 0

In [105]:
#Inventory Consistency
inventory_clean["Calculated_Closing_Stock"] = (
    inventory_clean["Opening_Stock"]
    + inventory_clean["Stock_In"]
    - inventory_clean["Stock_Out"]
).clip(lower=0)
inventory_errors = inventory_clean[
    inventory_clean["Closing_Stock"] !=
    inventory_clean["Calculated_Closing_Stock"]
].copy()

print("Inventory discrepancies:", len(inventory_errors))
inventory_clean["Inventory_Quality_Flag"] = "Valid"
print(inventory_clean["Inventory_Quality_Flag"].value_counts())

Inventory discrepancies: 0
Inventory_Quality_Flag
Valid    5000
Name: count, dtype: int64

In [106]:
#Purchase Order Calculation
#Subtotal = Quantity × Unit Cost
purchase_orders_clean["Calculated_Subtotal"] = (
    purchase_orders_clean["Quantity"] *
    purchase_orders_clean["Unit_Cost_INR"]
)

po_errors = purchase_orders_clean[
    abs(
        purchase_orders_clean["Subtotal_INR"]
        - purchase_orders_clean["Calculated_Subtotal"]
    ) > 1
]

print("Purchase Order subtotal discrepancies:",
      len(po_errors))

Purchase Order subtotal discrepancies: 0

In [107]:
#Create the Data Quality Report
quality_report = pd.DataFrame({
    "Check": [
        "PO → Supplier",
        "PO → Warehouse",
        "PO → Contract",
        "Inventory → PO",
        "Inventory → Warehouse",
        "Invoice → PO",
        "Invoice → Supplier",
        "Negative Quantity",
        "Negative Unit Cost",
        "Invalid Import Duty %",
        "Inventory Discrepancies",
        "PO Subtotal Discrepancies",
        "Negative Invoice Amount"
    ],
    
    "Invalid_Records": [
        check_foreign_key(purchase_orders_clean, "Supplier_ID",
                          suppliers_clean, "Supplier_ID"),
        
        check_foreign_key(purchase_orders_clean, "Warehouse_ID",
                          warehouses_clean, "Warehouse_ID"),
        
        check_foreign_key(po_with_contract, "Contract_ID",
                          contracts_clean, "Contract_ID"),
        
        check_foreign_key(inventory_clean, "PO_ID",
                          purchase_orders_clean, "PO_ID"),
        
        check_foreign_key(inventory_clean, "Warehouse_ID",
                          warehouses_clean, "Warehouse_ID"),
        
        check_foreign_key(invoices_clean, "PO_ID",
                          purchase_orders_clean, "PO_ID"),
        
        check_foreign_key(invoices_clean, "Supplier_ID",
                          suppliers_clean, "Supplier_ID"),
        
        (purchase_orders_clean["Quantity"] < 0).sum(),
        
        (purchase_orders_clean["Unit_Cost_INR"] < 0).sum(),
        
        ((purchase_orders_clean["Import_Duty_Percent"] < 0) |
         (purchase_orders_clean["Import_Duty_Percent"] > 100)).sum(),
        
        len(inventory_errors),
        
        len(po_errors),
        
        (invoices_clean["Invoice_Amount_INR"] < 0).sum()
    ]
})

display(quality_report)

                        Check  Invalid_Records
0               PO → Supplier                0
1              PO → Warehouse                0
2               PO → Contract                0
3              Inventory → PO                0
4       Inventory → Warehouse                0
5                Invoice → PO                0
6          Invoice → Supplier                0
7           Negative Quantity                0
8          Negative Unit Cost                0
9       Invalid Import Duty %                0
10    Inventory Discrepancies                0
11  PO Subtotal Discrepancies                0
12    Negative Invoice Amount                0