# Sprint 2 - Data Profiling and Data Quality

This notebook profiles, cleans, standardizes, and validates the six procurement datasets used in the project.

**Datasets:** `suppliers.csv`, `contracts.csv`, `purchase_orders.xlsx`, `inventory.json`, `warehouse.json`, `invoices.xml`.

In [1]:
import pandas as pd
from pathlib import Path

DATA_DIR = Path("../../datasets")

suppliers = pd.read_csv(DATA_DIR / "suppliers.csv")
contracts = pd.read_csv(DATA_DIR / "contracts.csv")
purchase_orders = pd.read_excel(DATA_DIR / "purchase_orders.xlsx")
inventory = pd.read_json(DATA_DIR / "inventory.json")
warehouse = pd.read_json(DATA_DIR / "warehouse.json")
invoices = pd.read_xml(DATA_DIR / "invoices.xml")

print("All datasets loaded successfully!")
print("\nDataset sizes:")
print("Suppliers:", suppliers.shape)
print("Contracts:", contracts.shape)
print("Purchase Orders:", purchase_orders.shape)
print("Inventory:", inventory.shape)
print("Warehouse:", warehouse.shape)
print("Invoices:", invoices.shape)

All datasets loaded successfully!

Dataset sizes:
Suppliers: (250, 10)
Contracts: (600, 10)
Purchase Orders: (5000, 23)
Inventory: (5000, 14)
Warehouse: (10, 8)
Invoices: (5000, 13)

## 1. Dataset Overview

In [2]:
datasets = {
    "Purchase Orders": purchase_orders,
    "Suppliers": suppliers,
    "Warehouses": warehouse,
    "Contracts": contracts,
    "Inventory": inventory,
    "Invoices": invoices
}

for name, df in datasets.items():
    print(f"\n{name}")
    print("Rows:", df.shape[0])
    print("Columns:", df.shape[1])
    print("-" * 40)

Purchase Orders
Rows: 5000
Columns: 23
----------------------------------------

Suppliers
Rows: 250
Columns: 10
----------------------------------------

Warehouses
Rows: 10
Columns: 8
----------------------------------------

Contracts
Rows: 600
Columns: 10
----------------------------------------

Inventory
Rows: 5000
Columns: 14
----------------------------------------

Invoices
Rows: 5000
Columns: 13
----------------------------------------

## 2. Column Names and Data Types

In [3]:
for name, df in datasets.items():
    print(f"\n{name}")
    print(df.dtypes)

Purchase Orders
PO_ID                      object
PO_Date                    object
Supplier_ID                object
Product_ID                 object
Warehouse_ID               object
Contract_ID                object
Supply_Type                object
Quantity                    int64
Unit_Cost_INR             float64
Subtotal_INR              float64
Freight_INR               float64
Import_Duty_Percent       float64
Import_Duty_INR           float64
Tax_INR                   float64
Total_PO_Value_INR        float64
Currency                   object
Exchange_Rate_to_INR      float64
Shipping_Mode              object
Expected_Delivery_Date     object
Actual_Receipt_Date        object
Delay_Days                  int64
Approval_Status            object
PO_Status                  object
dtype: object

Suppliers
Supplier_ID               object
Supplier_Name             object
Supplier_Type             object
Supplier_Country          object
Supplier_City             object
Primary_Category          object
Supplier_Rating           object
Typical_Lead_Time_Days     int64
Supplier_Status           object
Currency                  object
dtype: object

Warehouses
Warehouse_ID         object
Warehouse_Name       object
City                 object
Country              object
Warehouse_Type       object
Capacity_Units        int64
Storage_Condition    object
Warehouse_Status     object
dtype: object

Contracts
Contract_ID            object
Supplier_ID            object
Contract_Name          object
Start_Date             object
End_Date               object
Contract_Value        float64
Currency               object
Contract_Type          object
Contract_Status        object
Payment_Terms_Days      int64
dtype: object

Inventory
Inventory_ID                     object
PO_ID                            object
Product_ID                       object
Warehouse_ID                     object
Snapshot_Date                    object
Opening_Stock                     int64
Stock_In                          int64
Stock_Out                         int64
Closing_Stock                     int64
Reorder_Level                     int64
Safety_Stock                      int64
Inventory_Value_INR             float64
Stock_Status                     object
Capacity_Utilization_Percent    float64
dtype: object

Invoices
Invoice_ID                  object
PO_ID                       object
Supplier_ID                 object
Invoice_Date                object
Receipt_Date                object
Due_Date                    object
Invoice_Amount_INR         float64
Currency                    object
Exchange_Rate_to_INR       float64
Payment_Status              object
Paid_Date                   object
Matching_Status             object
Invoice_Approval_Status     object
dtype: object

## 3. Missing-Value Analysis

In [4]:
for name, df in datasets.items():
    print(f"\n{name}")
    print(df.isnull().sum())

Purchase Orders
PO_ID                       0
PO_Date                     0
Supplier_ID                 0
Product_ID                  0
Warehouse_ID                0
Contract_ID               276
Supply_Type                 0
Quantity                    0
Unit_Cost_INR               0
Subtotal_INR                0
Freight_INR                 0
Import_Duty_Percent         0
Import_Duty_INR             0
Tax_INR                     0
Total_PO_Value_INR          0
Currency                    0
Exchange_Rate_to_INR        0
Shipping_Mode               0
Expected_Delivery_Date      0
Actual_Receipt_Date         0
Delay_Days                  0
Approval_Status             0
PO_Status                   0
dtype: int64

Suppliers
Supplier_ID               0
Supplier_Name             0
Supplier_Type             0
Supplier_Country          0
Supplier_City             0
Primary_Category          0
Supplier_Rating           0
Typical_Lead_Time_Days    0
Supplier_Status           0
Currency                  0
dtype: int64

Warehouses
Warehouse_ID         0
Warehouse_Name       0
City                 0
Country              0
Warehouse_Type       0
Capacity_Units       0
Storage_Condition    0
Warehouse_Status     0
dtype: int64

Contracts
Contract_ID           0
Supplier_ID           0
Contract_Name         0
Start_Date            0
End_Date              0
Contract_Value        0
Currency              0
Contract_Type         0
Contract_Status       0
Payment_Terms_Days    0
dtype: int64

Inventory
Inventory_ID                    0
PO_ID                           0
Product_ID                      0
Warehouse_ID                    0
Snapshot_Date                   0
Opening_Stock                   0
Stock_In                        0
Stock_Out                       0
Closing_Stock                   0
Reorder_Level                   0
Safety_Stock                    0
Inventory_Value_INR             0
Stock_Status                    0
Capacity_Utilization_Percent    0
dtype: int64

Invoices
Invoice_ID                    0
PO_ID                         0
Supplier_ID                   0
Invoice_Date                  0
Receipt_Date                  0
Due_Date                      0
Invoice_Amount_INR            0
Currency                      0
Exchange_Rate_to_INR          0
Payment_Status                0
Paid_Date                  1630
Matching_Status               0
Invoice_Approval_Status       0
dtype: int64

## 4. Duplicate Row Analysis

In [5]:
for name, df in datasets.items():
    print(f"{name} - duplicate rows:", df.duplicated().sum())
    print("-" * 40)

Purchase Orders - duplicate rows: 0
----------------------------------------
Suppliers - duplicate rows: 0
----------------------------------------
Warehouses - duplicate rows: 0
----------------------------------------
Contracts - duplicate rows: 0
----------------------------------------
Inventory - duplicate rows: 0
----------------------------------------
Invoices - duplicate rows: 0
----------------------------------------

## 5. Primary-Key Validation

`PO_ID` is the primary key for Purchase Orders. `Product_ID` is not the primary key because the same product can occur in multiple purchase orders.

In [6]:
primary_keys = {
    "Purchase Orders": "PO_ID",
    "Suppliers": "Supplier_ID",
    "Warehouses": "Warehouse_ID",
    "Contracts": "Contract_ID",
    "Inventory": "Inventory_ID",
    "Invoices": "Invoice_ID"
}

for name, df in datasets.items():
    key = primary_keys[name]
    print(name)
    print("Primary Key:", key)
    print("Duplicate", key, ":", df[key].duplicated().sum())
    print()

Purchase Orders
Primary Key: PO_ID
Duplicate PO_ID : 0

Suppliers
Primary Key: Supplier_ID
Duplicate Supplier_ID : 0

Warehouses
Primary Key: Warehouse_ID
Duplicate Warehouse_ID : 0

Contracts
Primary Key: Contract_ID
Duplicate Contract_ID : 0

Inventory
Primary Key: Inventory_ID
Duplicate Inventory_ID : 0

Invoices
Primary Key: Invoice_ID
Duplicate Invoice_ID : 0

## 6. Basic Statistics

In [7]:
for name, df in datasets.items():
    print(f"\n{name}")
    display(df.describe())

Purchase Orders

,Quantity,Unit_Cost_INR,Subtotal_INR,Freight_INR,Import_Duty_Percent,Import_Duty_INR,Tax_INR,Total_PO_Value_INR,Exchange_Rate_to_INR,Delay_Days
count,5000.000000,5000.000000,5.000000e+03,5.000000e+03,5000.000000,5.000000e+03,5.000000e+03,5.000000e+03,5000.000000,5000.000000
mean,513.416800,45647.136648,2.350277e+07,4.415225e+05,5.033298,1.184048e+06,3.254290e+06,2.838263e+07,30.014536,1.451400
std,286.018167,24030.791375,1.920707e+07,4.891583e+05,6.012039,2.054940e+06,3.001970e+06,2.321438e+07,38.423279,2.383689
min,10.000000,385.220000,5.096080e+03,3.831000e+01,0.000000,0.000000e+00,9.241900e+02,6.058580e+03,0.560000,0.000000
25%,267.000000,26563.415000,7.503377e+06,1.047683e+05,0.000000,0.000000e+00,9.256132e+05,9.064173e+06,1.000000,0.000000
50%,523.000000,44674.130000,1.889416e+07,2.821170e+05,1.000000,1.126325e+03,2.337941e+06,2.273666e+07,1.000000,0.000000
75%,760.000000,66541.400000,3.539231e+07,6.008577e+05,10.032500,1.575361e+06,4.702517e+06,4.289306e+07,62.000000,2.000000
max,1000.000000,93178.590000,8.923069e+07,3.745332e+06,18.000000,1.408533e+07,1.596581e+07,1.133647e+08,106.000000,12.000000

Suppliers

       Typical_Lead_Time_Days
count              250.000000
mean                17.508000
std                  7.959356
min                  5.000000
25%                 11.000000
50%                 17.000000
75%                 24.000000
max                 30.000000

Warehouses

       Capacity_Units
count       10.000000
mean     20878.500000
std       6808.841707
min       5767.000000
25%      18994.000000
50%      21967.000000
75%      25795.250000
max      28951.000000

Contracts

       Contract_Value  Payment_Terms_Days
count    6.000000e+02          600.000000
mean     7.616079e+06           56.925000
std      4.343741e+06           22.299061
min      1.724478e+05           30.000000
25%      3.768706e+06           45.000000
50%      7.690013e+06           60.000000
75%      1.141667e+07           90.000000
max      1.499659e+07           90.000000

Inventory

,Opening_Stock,Stock_In,Stock_Out,Closing_Stock,Reorder_Level,Safety_Stock,Inventory_Value_INR,Capacity_Utilization_Percent
count,5000.000000,5000.000000,5000.000000,5000.000000,5000.000000,5000.000000,5.000000e+03,5000.000000
mean,525.623400,513.416800,392.202600,654.579800,264.511800,126.388600,2.964971e+07,3.769950
std,439.993149,286.018167,337.239427,498.282645,135.942021,70.415692,3.011763e+07,4.166375
min,0.000000,10.000000,0.000000,0.000000,22.000000,11.000000,0.000000e+00,0.000000
25%,152.750000,267.000000,112.750000,247.000000,163.000000,65.000000,6.940223e+06,1.210000
50%,410.000000,523.000000,293.000000,571.000000,256.000000,118.000000,2.038508e+07,2.780000
75%,796.000000,760.000000,609.000000,976.000000,379.000000,184.000000,4.284091e+07,4.910000
max,1980.000000,1000.000000,1497.000000,2589.000000,499.000000,250.000000,1.942664e+08,41.270000

Invoices

       Invoice_Amount_INR  Exchange_Rate_to_INR
count        5.000000e+03           5000.000000
mean         2.838263e+07             30.014536
std          2.321438e+07             38.423279
min          6.058580e+03              0.560000
25%          9.064173e+06              1.000000
50%          2.273666e+07              1.000000
75%          4.289306e+07             62.000000
max          1.133647e+08            106.000000

## 7. Overall Profiling Report

In [8]:
profiling_report = []

for name, df in datasets.items():
    for column in df.columns:
        profiling_report.append({
            "Dataset": name,
            "Column": column,
            "Data_Type": str(df[column].dtype),
            "Total_Records": len(df),
            "Missing_Values": int(df[column].isnull().sum()),
            "Missing_%": round(df[column].isnull().mean() * 100, 2),
            "Unique_Values": int(df[column].nunique()),
            "Duplicate_Values": int(df[column].duplicated().sum())
        })

profiling_report = pd.DataFrame(profiling_report)
display(profiling_report)

,Dataset,Column,Data_Type,Total_Records,Missing_Values,Missing_%,Unique_Values,Duplicate_Values
0,Purchase Orders,PO_ID,object,5000,0,0.0,5000,0
1,Purchase Orders,PO_Date,object,5000,0,0.0,581,4419
2,Purchase Orders,Supplier_ID,object,5000,0,0.0,250,4750
3,Purchase Orders,Product_ID,object,5000,0,0.0,300,4700
4,Purchase Orders,Warehouse_ID,object,5000,0,0.0,10,4990
...,...,...,...,...,...,...,...,...
73,Invoices,Exchange_Rate_to_INR,float64,5000,0,0.0,9,4991
74,Invoices,Payment_Status,object,5000,0,0.0,4,4996
75,Invoices,Paid_Date,object,5000,1630,32.6,641,4358
76,Invoices,Matching_Status,object,5000,0,0.0,2,4998
77,Invoices,Invoice_Approval_Status,object,5000,0,0.0,2,4998

## 8. Missing-Value Report

In [9]:
missing_report = []

for name, df in datasets.items():
    for column in df.columns:
        missing = int(df[column].isnull().sum())
        missing_report.append({
            "Dataset": name,
            "Column": column,
            "Missing_Values": missing,
            "Missing_Percentage": round((missing / len(df)) * 100, 2)
        })

missing_report = pd.DataFrame(missing_report)
display(missing_report)

,Dataset,Column,Missing_Values,Missing_Percentage
0,Purchase Orders,PO_ID,0,0.0
1,Purchase Orders,PO_Date,0,0.0
2,Purchase Orders,Supplier_ID,0,0.0
3,Purchase Orders,Product_ID,0,0.0
4,Purchase Orders,Warehouse_ID,0,0.0
...,...,...,...,...
73,Invoices,Exchange_Rate_to_INR,0,0.0
74,Invoices,Payment_Status,0,0.0
75,Invoices,Paid_Date,1630,32.6
76,Invoices,Matching_Status,0,0.0
77,Invoices,Invoice_Approval_Status,0,0.0

## 9. Duplicate-Key Report

In [10]:
duplicate_report = []

for name, df in datasets.items():
    key = primary_keys[name]
    duplicate_report.append({
        "Dataset": name,
        "Primary_Key": key,
        "Total_Rows": len(df),
        "Duplicate_Rows": int(df.duplicated().sum()),
        "Duplicate_Keys": int(df[key].duplicated().sum())
    })

duplicate_report = pd.DataFrame(duplicate_report)
display(duplicate_report)

           Dataset   Primary_Key  Total_Rows  Duplicate_Rows  Duplicate_Keys
0  Purchase Orders         PO_ID        5000               0               0
1        Suppliers   Supplier_ID         250               0               0
2       Warehouses  Warehouse_ID          10               0               0
3        Contracts   Contract_ID         600               0               0
4        Inventory  Inventory_ID        5000               0               0
5         Invoices    Invoice_ID        5000               0               0

## 10. Referential-Integrity Checks

In [11]:
def check_foreign_key(child_df, child_column, parent_df, parent_column, ignore_null=True):
    child_values = child_df[child_column]
    if ignore_null:
        child_values = child_values.dropna()
    invalid = child_values[~child_values.isin(parent_df[parent_column])]
    return int(len(invalid))

print("Purchase Orders → Suppliers:",
      check_foreign_key(purchase_orders, "Supplier_ID", suppliers, "Supplier_ID"))

print("Purchase Orders → Warehouses:",
      check_foreign_key(purchase_orders, "Warehouse_ID", warehouse, "Warehouse_ID"))

print("Inventory → Purchase Orders:",
      check_foreign_key(inventory, "PO_ID", purchase_orders, "PO_ID"))

print("Inventory → Warehouses:",
      check_foreign_key(inventory, "Warehouse_ID", warehouse, "Warehouse_ID"))

print("Invoices → Purchase Orders:",
      check_foreign_key(invoices, "PO_ID", purchase_orders, "PO_ID"))

print("Invoices → Suppliers:",
      check_foreign_key(invoices, "Supplier_ID", suppliers, "Supplier_ID"))

Purchase Orders → Suppliers: 0
Purchase Orders → Warehouses: 0
Inventory → Purchase Orders: 0
Inventory → Warehouses: 0
Invoices → Purchase Orders: 0
Invoices → Suppliers: 0

## 11. Create Clean Copies

In [12]:
suppliers_clean = suppliers.copy()
contracts_clean = contracts.copy()
warehouses_clean = warehouse.copy()
purchase_orders_clean = purchase_orders.copy()
inventory_clean = inventory.copy()
invoices_clean = invoices.copy()

## 12. Standardize Column Names

In [13]:
def standardize_columns(df):
    df = df.copy()
    df.columns = (
        df.columns
        .str.strip()
        .str.replace(" ", "_", regex=False)
        .str.replace("-", "_", regex=False)
    )
    return df

suppliers_clean = standardize_columns(suppliers_clean)
warehouses_clean = standardize_columns(warehouses_clean)
purchase_orders_clean = standardize_columns(purchase_orders_clean)
contracts_clean = standardize_columns(contracts_clean)
inventory_clean = standardize_columns(inventory_clean)
invoices_clean = standardize_columns(invoices_clean)

suppliers_clean = suppliers_clean.drop_duplicates().copy()
warehouses_clean = warehouses_clean.drop_duplicates().copy()
purchase_orders_clean = purchase_orders_clean.drop_duplicates().copy()
contracts_clean = contracts_clean.drop_duplicates().copy()
inventory_clean = inventory_clean.drop_duplicates().copy()
invoices_clean = invoices_clean.drop_duplicates().copy()

## 13. Remove Extra Spaces from Text Fields

In [14]:
def clean_text_columns(df):
    df = df.copy()
    for col in df.select_dtypes(include="object").columns:
        df[col] = df[col].str.strip()
    return df

suppliers_clean = clean_text_columns(suppliers_clean)
warehouses_clean = clean_text_columns(warehouses_clean)
purchase_orders_clean = clean_text_columns(purchase_orders_clean)
inventory_clean = clean_text_columns(inventory_clean)
contracts_clean = clean_text_columns(contracts_clean)
invoices_clean = clean_text_columns(invoices_clean)

## 14. Handle Missing Values

- Missing `Contract_ID` is represented as `No Contract`.
- Missing `Paid_Date` is kept as missing because an unpaid invoice does not have a payment date. `Payment_Status` already records the payment state.

In [15]:
purchase_orders_clean["Contract_ID"] = (
    purchase_orders_clean["Contract_ID"].fillna("No Contract")
)

print("Missing Contract_ID:",
      purchase_orders_clean["Contract_ID"].isnull().sum())

print("Missing Paid_Date before date conversion:",
      invoices_clean["Paid_Date"].isnull().sum())

Missing Contract_ID: 0
Missing Paid_Date before date conversion: 1630

## 15. Convert Date Columns

In [16]:
date_columns = {
    "Purchase Orders": (purchase_orders_clean,
                        ["PO_Date", "Expected_Delivery_Date", "Actual_Receipt_Date"]),
    "Contracts": (contracts_clean, ["Start_Date", "End_Date"]),
    "Inventory": (inventory_clean, ["Snapshot_Date"]),
    "Invoices": (invoices_clean,
                 ["Invoice_Date", "Receipt_Date", "Due_Date", "Paid_Date"])
}

date_conversion_report = []

for dataset_name, (df, columns) in date_columns.items():
    for column in columns:
        original_missing = int(df[column].isnull().sum())
        df[column] = pd.to_datetime(df[column], errors="coerce")
        final_missing = int(df[column].isnull().sum())

        date_conversion_report.append({
            "Dataset": dataset_name,
            "Column": column,
            "Original_Missing": original_missing,
            "Final_Missing": final_missing,
            "New_Invalid_or_Unparseable": max(final_missing - original_missing, 0)
        })

date_conversion_report = pd.DataFrame(date_conversion_report)
display(date_conversion_report)

C:\Users\Jaheen\AppData\Local\Temp\ipykernel_17256\730705170.py:15: UserWarning: Parsing dates in %d-%m-%Y format when dayfirst=False (the default) was specified. Pass `dayfirst=True` or specify a format to silence this warning.
  df[column] = pd.to_datetime(df[column], errors="coerce")
C:\Users\Jaheen\AppData\Local\Temp\ipykernel_17256\730705170.py:15: UserWarning: Parsing dates in %d-%m-%Y format when dayfirst=False (the default) was specified. Pass `dayfirst=True` or specify a format to silence this warning.
  df[column] = pd.to_datetime(df[column], errors="coerce")
C:\Users\Jaheen\AppData\Local\Temp\ipykernel_17256\730705170.py:15: UserWarning: Parsing dates in %d-%m-%Y format when dayfirst=False (the default) was specified. Pass `dayfirst=True` or specify a format to silence this warning.
  df[column] = pd.to_datetime(df[column], errors="coerce")
C:\Users\Jaheen\AppData\Local\Temp\ipykernel_17256\730705170.py:15: UserWarning: Parsing dates in %d-%m-%Y format when dayfirst=False (the default) was specified. Pass `dayfirst=True` or specify a format to silence this warning.
  df[column] = pd.to_datetime(df[column], errors="coerce")
C:\Users\Jaheen\AppData\Local\Temp\ipykernel_17256\730705170.py:15: UserWarning: Parsing dates in %d-%m-%Y format when dayfirst=False (the default) was specified. Pass `dayfirst=True` or specify a format to silence this warning.
  df[column] = pd.to_datetime(df[column], errors="coerce")

,Dataset,Column,Original_Missing,Final_Missing,New_Invalid_or_Unparseable
0,Purchase Orders,PO_Date,0,0,0
1,Purchase Orders,Expected_Delivery_Date,0,0,0
2,Purchase Orders,Actual_Receipt_Date,0,0,0
3,Contracts,Start_Date,0,0,0
4,Contracts,End_Date,0,0,0
5,Inventory,Snapshot_Date,0,0,0
6,Invoices,Invoice_Date,0,0,0
7,Invoices,Receipt_Date,0,0,0
8,Invoices,Due_Date,0,3001,3001
9,Invoices,Paid_Date,1630,3646,2016

## 16. Check Data Types After Cleaning

In [17]:
cleaned_datasets = {
    "Purchase Orders": purchase_orders_clean,
    "Suppliers": suppliers_clean,
    "Warehouses": warehouses_clean,
    "Contracts": contracts_clean,
    "Inventory": inventory_clean,
    "Invoices": invoices_clean
}

for name, df in cleaned_datasets.items():
    print(f"\n{name}")
    print(df.dtypes)

Purchase Orders
PO_ID                             object
PO_Date                   datetime64[ns]
Supplier_ID                       object
Product_ID                        object
Warehouse_ID                      object
Contract_ID                       object
Supply_Type                       object
Quantity                           int64
Unit_Cost_INR                    float64
Subtotal_INR                     float64
Freight_INR                      float64
Import_Duty_Percent              float64
Import_Duty_INR                  float64
Tax_INR                          float64
Total_PO_Value_INR               float64
Currency                          object
Exchange_Rate_to_INR             float64
Shipping_Mode                     object
Expected_Delivery_Date    datetime64[ns]
Actual_Receipt_Date       datetime64[ns]
Delay_Days                         int64
Approval_Status                   object
PO_Status                         object
dtype: object

Suppliers
Supplier_ID               object
Supplier_Name             object
Supplier_Type             object
Supplier_Country          object
Supplier_City             object
Primary_Category          object
Supplier_Rating           object
Typical_Lead_Time_Days     int64
Supplier_Status           object
Currency                  object
dtype: object

Warehouses
Warehouse_ID         object
Warehouse_Name       object
City                 object
Country              object
Warehouse_Type       object
Capacity_Units        int64
Storage_Condition    object
Warehouse_Status     object
dtype: object

Contracts
Contract_ID                   object
Supplier_ID                   object
Contract_Name                 object
Start_Date            datetime64[ns]
End_Date              datetime64[ns]
Contract_Value               float64
Currency                      object
Contract_Type                 object
Contract_Status               object
Payment_Terms_Days             int64
dtype: object

Inventory
Inventory_ID                            object
PO_ID                                   object
Product_ID                              object
Warehouse_ID                            object
Snapshot_Date                   datetime64[ns]
Opening_Stock                            int64
Stock_In                                 int64
Stock_Out                                int64
Closing_Stock                            int64
Reorder_Level                            int64
Safety_Stock                             int64
Inventory_Value_INR                    float64
Stock_Status                            object
Capacity_Utilization_Percent           float64
dtype: object

Invoices
Invoice_ID                         object
PO_ID                              object
Supplier_ID                        object
Invoice_Date               datetime64[ns]
Receipt_Date               datetime64[ns]
Due_Date                   datetime64[ns]
Invoice_Amount_INR                float64
Currency                           object
Exchange_Rate_to_INR              float64
Payment_Status                     object
Paid_Date                  datetime64[ns]
Matching_Status                    object
Invoice_Approval_Status            object
dtype: object

## 17. Check Remaining Missing Values

In [18]:
for name, df in cleaned_datasets.items():
    remaining = df.isnull().sum()
    remaining = remaining[remaining > 0]
    print(f"\n{name}")
    print("No missing values." if remaining.empty else remaining)

Purchase Orders
No missing values.

Suppliers
No missing values.

Warehouses
No missing values.

Contracts
No missing values.

Inventory
No missing values.

Invoices
Due_Date     3001
Paid_Date    3646
dtype: int64

## 18. Referential Integrity After Cleaning

In [19]:
print("Purchase Orders → Suppliers:",
      check_foreign_key(purchase_orders_clean, "Supplier_ID",
                        suppliers_clean, "Supplier_ID"))

print("Purchase Orders → Warehouses:",
      check_foreign_key(purchase_orders_clean, "Warehouse_ID",
                        warehouses_clean, "Warehouse_ID"))

po_with_contract = purchase_orders_clean[
    purchase_orders_clean["Contract_ID"] != "No Contract"
]

print("Purchase Orders → Contracts:",
      check_foreign_key(po_with_contract, "Contract_ID",
                        contracts_clean, "Contract_ID"))

print("Inventory → Purchase Orders:",
      check_foreign_key(inventory_clean, "PO_ID",
                        purchase_orders_clean, "PO_ID"))

print("Inventory → Warehouses:",
      check_foreign_key(inventory_clean, "Warehouse_ID",
                        warehouses_clean, "Warehouse_ID"))

print("Invoices → Purchase Orders:",
      check_foreign_key(invoices_clean, "PO_ID",
                        purchase_orders_clean, "PO_ID"))

print("Invoices → Suppliers:",
      check_foreign_key(invoices_clean, "Supplier_ID",
                        suppliers_clean, "Supplier_ID"))

Purchase Orders → Suppliers: 0
Purchase Orders → Warehouses: 0
Purchase Orders → Contracts: 0
Inventory → Purchase Orders: 0
Inventory → Warehouses: 0
Invoices → Purchase Orders: 0
Invoices → Suppliers: 0

## 19. Purchase Order Range Validation

In [20]:
po_range_checks = {
    "Negative Quantity": purchase_orders_clean["Quantity"] < 0,
    "Negative Unit Cost": purchase_orders_clean["Unit_Cost_INR"] < 0,
    "Invalid Import Duty %": (
        (purchase_orders_clean["Import_Duty_Percent"] < 0) |
        (purchase_orders_clean["Import_Duty_Percent"] > 100)
    ),
    "Negative Total PO Value": purchase_orders_clean["Total_PO_Value_INR"] < 0
}

for check_name, condition in po_range_checks.items():
    print(f"{check_name}: {int(condition.sum())}")

Negative Quantity: 0
Negative Unit Cost: 0
Invalid Import Duty %: 0
Negative Total PO Value: 0

## 20. Inventory Range Validation

In [21]:
inventory_range_checks = {
    "Negative Opening Stock": inventory_clean["Opening_Stock"] < 0,
    "Negative Stock In": inventory_clean["Stock_In"] < 0,
    "Negative Stock Out": inventory_clean["Stock_Out"] < 0,
    "Negative Closing Stock": inventory_clean["Closing_Stock"] < 0,
    "Invalid Capacity Utilization": (
        (inventory_clean["Capacity_Utilization_Percent"] < 0) |
        (inventory_clean["Capacity_Utilization_Percent"] > 100)
    )
}

for check_name, condition in inventory_range_checks.items():
    print(f"{check_name}: {int(condition.sum())}")

Negative Opening Stock: 0
Negative Stock In: 0
Negative Stock Out: 0
Negative Closing Stock: 0
Invalid Capacity Utilization: 0

## 21. Invoice Range Validation

In [22]:
invoice_range_checks = {
    "Negative Invoice Amount": invoices_clean["Invoice_Amount_INR"] < 0,
    "Negative Exchange Rate": invoices_clean["Exchange_Rate_to_INR"] < 0
}

for check_name, condition in invoice_range_checks.items():
    print(f"{check_name}: {int(condition.sum())}")

Negative Invoice Amount: 0
Negative Exchange Rate: 0

## 22. Inventory Consistency Validation

Business rule:

`Closing Stock = Opening Stock + Stock In - Stock Out`

The quality flag is calculated from the actual comparison instead of marking every row as valid automatically.

In [23]:
inventory_clean["Calculated_Closing_Stock"] = (
    inventory_clean["Opening_Stock"]
    + inventory_clean["Stock_In"]
    - inventory_clean["Stock_Out"]
)

inventory_errors = inventory_clean[
    inventory_clean["Closing_Stock"] != inventory_clean["Calculated_Closing_Stock"]
].copy()

inventory_clean["Inventory_Quality_Flag"] = "Valid"
inventory_clean.loc[
    inventory_clean["Closing_Stock"] != inventory_clean["Calculated_Closing_Stock"],
    "Inventory_Quality_Flag"
] = "Invalid"

print("Inventory discrepancies:", len(inventory_errors))
print(inventory_clean["Inventory_Quality_Flag"].value_counts())

Inventory discrepancies: 330
Inventory_Quality_Flag
Valid      4670
Invalid     330
Name: count, dtype: int64

## 23. Purchase Order Calculation Validation

Business rule:

`Subtotal = Quantity × Unit Cost`

A tolerance of 1 INR is used for small rounding differences.

In [24]:
purchase_orders_clean["Calculated_Subtotal"] = (
    purchase_orders_clean["Quantity"] *
    purchase_orders_clean["Unit_Cost_INR"]
)

po_errors = purchase_orders_clean[
    (
        purchase_orders_clean["Subtotal_INR"] -
        purchase_orders_clean["Calculated_Subtotal"]
    ).abs() > 1
].copy()

print("Purchase Order subtotal discrepancies:", len(po_errors))

Purchase Order subtotal discrepancies: 0

## 24. Final Data Quality Report

In [25]:
quality_checks = []

def add_quality_check(dataset, check, invalid_count):
    invalid_count = int(invalid_count)
    quality_checks.append({
        "Dataset": dataset,
        "Check": check,
        "Invalid_Count": invalid_count,
        "Status": "PASS" if invalid_count == 0 else "REVIEW"
    })

for name, df in cleaned_datasets.items():
    key = primary_keys[name]
    add_quality_check(name, f"Duplicate {key}", df[key].duplicated().sum())
    add_quality_check(name, "Remaining missing values", df.isnull().sum().sum())

add_quality_check(
    "Purchase Orders", "Supplier_ID foreign key",
    check_foreign_key(purchase_orders_clean, "Supplier_ID",
                      suppliers_clean, "Supplier_ID")
)
add_quality_check(
    "Purchase Orders", "Warehouse_ID foreign key",
    check_foreign_key(purchase_orders_clean, "Warehouse_ID",
                      warehouses_clean, "Warehouse_ID")
)
add_quality_check(
    "Purchase Orders", "Contract_ID foreign key excluding No Contract",
    check_foreign_key(po_with_contract, "Contract_ID",
                      contracts_clean, "Contract_ID")
)
add_quality_check(
    "Inventory", "PO_ID foreign key",
    check_foreign_key(inventory_clean, "PO_ID",
                      purchase_orders_clean, "PO_ID")
)
add_quality_check(
    "Inventory", "Warehouse_ID foreign key",
    check_foreign_key(inventory_clean, "Warehouse_ID",
                      warehouses_clean, "Warehouse_ID")
)
add_quality_check(
    "Invoices", "PO_ID foreign key",
    check_foreign_key(invoices_clean, "PO_ID",
                      purchase_orders_clean, "PO_ID")
)
add_quality_check(
    "Invoices", "Supplier_ID foreign key",
    check_foreign_key(invoices_clean, "Supplier_ID",
                      suppliers_clean, "Supplier_ID")
)

for check_name, condition in po_range_checks.items():
    add_quality_check("Purchase Orders", check_name, condition.sum())

for check_name, condition in inventory_range_checks.items():
    add_quality_check("Inventory", check_name, condition.sum())

for check_name, condition in invoice_range_checks.items():
    add_quality_check("Invoices", check_name, condition.sum())

add_quality_check("Inventory", "Closing stock calculation", len(inventory_errors))
add_quality_check("Purchase Orders", "Subtotal calculation", len(po_errors))

quality_report = pd.DataFrame(quality_checks)
display(quality_report)

,Dataset,Check,Invalid_Count,Status
0,Purchase Orders,Duplicate PO_ID,0,PASS
1,Purchase Orders,Remaining missing values,0,PASS
2,Suppliers,Duplicate Supplier_ID,0,PASS
3,Suppliers,Remaining missing values,0,PASS
4,Warehouses,Duplicate Warehouse_ID,0,PASS
5,Warehouses,Remaining missing values,0,PASS
6,Contracts,Duplicate Contract_ID,0,PASS
7,Contracts,Remaining missing values,0,PASS
8,Inventory,Duplicate Inventory_ID,0,PASS
9,Inventory,Remaining missing values,0,PASS
10,Invoices,Duplicate Invoice_ID,0,PASS
11,Invoices,Remaining missing values,6647,REVIEW
12,Purchase Orders,Supplier_ID foreign key,0,PASS
13,Purchase Orders,Warehouse_ID foreign key,0,PASS
14,Purchase Orders,Contract_ID foreign key excluding No Contract,0,PASS
15,Inventory,PO_ID foreign key,0,PASS
16,Inventory,Warehouse_ID foreign key,0,PASS
17,Invoices,PO_ID foreign key,0,PASS
18,Invoices,Supplier_ID foreign key,0,PASS
19,Purchase Orders,Negative Quantity,0,PASS
20,Purchase Orders,Negative Unit Cost,0,PASS
21,Purchase Orders,Invalid Import Duty %,0,PASS
22,Purchase Orders,Negative Total PO Value,0,PASS
23,Inventory,Negative Opening Stock,0,PASS
24,Inventory,Negative Stock In,0,PASS
25,Inventory,Negative Stock Out,0,PASS
26,Inventory,Negative Closing Stock,0,PASS
27,Inventory,Invalid Capacity Utilization,0,PASS
28,Invoices,Negative Invoice Amount,0,PASS
29,Invoices,Negative Exchange Rate,0,PASS
30,Inventory,Closing stock calculation,330,REVIEW
31,Purchase Orders,Subtotal calculation,0,PASS

## 25. Final Cleaned-Dataset Summary

In [26]:
final_summary = []

for name, df in cleaned_datasets.items():
    final_summary.append({
        "Dataset": name,
        "Rows": len(df),
        "Columns": len(df.columns),
        "Duplicate_Rows": int(df.duplicated().sum()),
        "Missing_Values": int(df.isnull().sum().sum())
    })

final_summary = pd.DataFrame(final_summary)
display(final_summary)

           Dataset  Rows  Columns  Duplicate_Rows  Missing_Values
0  Purchase Orders  5000       24               0               0
1        Suppliers   250       10               0               0
2       Warehouses    10        8               0               0
3        Contracts   600       10               0               0
4        Inventory  5000       16               0               0
5         Invoices  5000       13               0            6647

## 26. Sprint 2 Output

The notebook produces:

1. Dataset profiling
2. Missing-value analysis
3. Duplicate and primary-key validation
4. Referential-integrity checks
5. Column-name and text standardization
6. Missing-value handling
7. Date standardization
8. Range validation
9. Inventory consistency validation
10. Purchase-order subtotal validation
11. Final data-quality report

The cleaned DataFrames are ready for the PostgreSQL warehouse-loading stage.